"""Process the files generated by sphinx-apidoc. It removes the "Submodules" and "Subpackages" section headers to
reduce the nesting level.
"""
import os.path
import glob


def process_package(filename):
    with open(filename, 'r') as f:
        content = f.read()

    to_remove = ["Submodules\n----------",
                 "Subpackages\n-----------"]
    for tr in to_remove:
        content = content.replace(tr, '')

    with open(filename, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    file = __file__

    doc_source, _ = os.path.split(file)
    rst_pattern = os.path.join(doc_source, 'qupulse*.rst')
    rst_files = glob.glob(rst_pattern)
    for rst in rst_files:
        process_package(rst)
