%% 4 CHANs
pulseLocation = plsdata.path;
chargeScanPulse = qc.load_pulse('general_charge_scan', pulseLocation);

params = struct( ...
	'N_y', 10, ...
	't_wait', 0, ... % ns
	'y_stop', 1, ...
	'x_stop', 1, ...
	'x_start', -1, ...
	'N_x', 10, ...
	't_meas', 192, ...
	'y_start', -1, ...
	'W_fast', 0, ...
	'W_slow', 1, ...
	'X_fast', 1, ...
	'X_slow', 0, ...
	'Y_fast', 0, ...
	'Y_slow', 1, ...
	'Z_fast', 0, ...
	'Z_slow', 1, ...
	'rep_count', 1 ...
	);


%%
qc.plot_pulse(chargeScanPulse, params)

%% 4 CHANs upload and arm
qc.arm_pulse('general_charge_scan', ...
	'channel_mapping', struct('W', 'TABOR_A','X', 'TABOR_B','Y', 'TABOR_C', 'Z', 'TABOR_D', 'marker', 'TABOR_A_MARKER'), ...
	'window_mapping', struct('A', 'A', 'B', 'B'),...
	'update', py.True)

%%
qc.arm_pulse('general_charge_scan')