name: Publish Python Package

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tool
        run: python3 -m pip install --upgrade build
      - name: Build wheel & sdist
        run: python3 -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  test-publish:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    uses: ./.github/workflows/upload_to_repository.yml
    with:
      repository-url: https://test.pypi.org/legacy/
    secrets:
      pypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}

  publish:
    if: ${{ github.event_name == 'release' }}
    needs: build
    uses: ./.github/workflows/upload_to_repository.yml
    with:
      repository-url: https://upload.pypi.org/legacy/
    secrets:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
